# Generated by Django 2.0.1 on 2018-06-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180615_1542'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='relation',
            name='web_relatio_from_no_3bafe5_idx',
        ),
        migrations.RemoveIndex(
            model_name='similarity',
            name='web_similar_node_id_311dad_idx',
        ),
        migrations.AlterField(
            model_name='node',
            name='visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['from_node_id'], name='web_relatio_from_no_7d4962_idx'),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['to_node_id'], name='web_relatio_to_node_0fe8f8_idx'),
        ),
        migrations.AddIndex(
            model_name='similarity',
            index=models.Index(fields=['node_id'], name='web_similar_node_id_a27f08_idx'),
        ),
        migrations.AddIndex(
            model_name='similarity',
            index=models.Index(fields=['tag_id'], name='web_similar_tag_id_019d3e_idx'),
        ),
    ]
