# Generated by Django 2.0.1 on 2018-06-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180615_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('mail', models.CharField(max_length=128, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('salt', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('level', models.IntegerField(default=0)),
                ('node_id', models.IntegerField(null=True)),
                ('tag_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user_id'], name='web_userpre_user_id_5590aa_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['node_id'], name='web_userpre_node_id_56839e_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['tag_id'], name='web_userpre_tag_id_b7875c_idx'),
        ),
    ]
